# Generated by Django 3.0 on 2021-11-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Re_Enter_Password', models.CharField(max_length=50)),
            ],
        ),
    ]
