# Generated by Django 3.0 on 2021-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rural', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField(max_length=50)),
                ('PlaceOfBirth', models.CharField(max_length=50)),
                ('TimeOfBirth', models.TimeField(max_length=50)),
                ('Name_Of_Father', models.CharField(max_length=50)),
                ('Name_Of_Mother', models.CharField(max_length=50)),
                ('DateOfRegistration', models.DateField(max_length=50)),
                ('Registration_Number', models.CharField(max_length=40)),
            ],
        ),
    ]
