# Generated by Django 3.0 on 2021-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rural', '0004_death'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.AlterField(
            model_name='death',
            name='TimeOfDeath',
            field=models.TimeField(max_length=50),
        ),
    ]
